server:
  port: 18081
  
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240000
  http:
    encoding:
      enabled: true
      charset: utf-8
  jwt: 
    secretKey: H5hjgbDSAyyteE23uMNveppCUl
  
  #文件上传io操作临时目录
  io: 
    multipart: 
      tempDir: /srv/data/data-capture
  profiles:     #選擇開發環境     舊的服務器作爲測試環境dev     新的服務器作爲正式環境prod
    active: dev
     
mybatis:
  mapper-locations: classpath:mapper/*.xml
  
logging:
  path: logback-spring.xml