server:
  port: 18080
  
spring:
  datasource:
    url: jdbc:mysql://47.92.235.52:3306/data_manage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: W4d49vLvmx=
    driverClassName: com.mysql.jdbc.Driver
    #初始化大小，最小，最大
    initialSize: 8
    minIdle: 8
    maxActive: 100
    #获取连接等待超时时间
    maxWait: 1000
    testOnBorrow: true
    validationQuery: select 1 from dual
    #打开PSCache，并且指定每一个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，‘wall’用于防火墙
    filters: stat, wall, slf4j
    logSlowSql: true
    #通过connectProperties属性来打开mergeSql功能； 慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10240000
  http:
    encoding:
      enabled: true
      charset: utf-8
  jwt: 
    secretKey: H5hjgbDSAyyteE23uMNveppCUl
  
  #文件上传io操作临时目录
  io: 
    multipart: 
      tempDir: /srv/data/data-capture
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  
logging:
  path: logback-spring.xml